repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Replace with latest version from https://github.com/psf/black/tags
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6  # Replace with latest version from https://github.com/charliermarsh/ruff-pre-commit/tags
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Replace with latest version from https://github.com/pre-commit/mirrors-mypy/tags
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

default_stages: [pre-commit]
